descFVS_Cases=
"<b>FVS_Cases</b> contains information that identifies every stand in the simulation,
the time the run was made, the variant, the run title, and keyword file name. 
There is one row for each stand."

descFVS_Summary=
"<b>FVS_Summary</b> contains stand level summary statistics including the year,
stand density, tree volume, removals, plus overall growth and mortality rates. 
There is one row for each cycle year of the simulation. For the eastern FVS variants,
the table is called FVS_Summary_East and the content differs in how volumes 
are reported."

descFVS_Compute=
"<b>FVS_Compute</b> contains one column for each <i>compute variable</i> in the simulation
and one row for each stand and cycle year."

descFVS_DM_Stnd_Sum=
"<b>FVS_DM_Stnd_Sum</b> contains a stand level summary of the number of trees, basal area, 
and volume, that are not infected, infected, and the percent infected. There is one row
for each stand and cycle year."

descFVS_DM_Spp_Sum="<b>FVS_DM_Spp_Sum</b> contains a summary of the mistletoe rating scores,
the number of infected trees, the nuber of trees killed, all by cycle year and species. 
There is one row for each stand, cycle year, and species."

descFVS_DM_Sz_Sum=
"<b>FVS_DM_Sz_Sum</b> contains the number of infected trees and the number of trees killed
by mistletoe. There is one row for each stand, cycle year, 2-inch tree DBH class." 

descFVS_Treelist=
"<b>FVS_Treelist</b> contains information about the individual tree records held by FVS. The
number of trees represented by each tree record and information that includes tree species,
size, volume and so on, make up the columns. There is one row for every tree record, stand, and
cycle year. This table, plus the FVS_CutList table, are used to build stand and stock
tables."

descFVS_CutList=
"<b>FVS_CutList</b> is just like the FVS_Treelist table except that
the number of trees harvested during the cycle is reported rather than the number
standing as reported in the FVS_Treelist table. This table is output just in stands and cycles 
where there were removals; it is used with the FVS_Treelist table to generate stand
and stock tables."

descFVS_Carbon=
"<b>FVS_Carbon</b> is generated by the Fire and Fuels Extension. The table contains
above and below ground carbon loads for live, dead, snags, down wood, shrubs, and
carbon released by fire. There is one row for each stand and cycle year."

descFVS_Consumption=
"<b>FVS_Consumption</b> is generated by the Fire and Fuels Extension. For a simlated fire,
the table contains mineral soil exposeure, fuel consumed by category, and smoke 
produced by partical size. There is one row for each simulated fire."

descFVS_Hrv_Carbon=
"<b>FVS_Hrv_Carbon</b> is generated by the Fire and Fuels Extension. The table contains
the estimted abount of carbon that the stand generates in wood products, added to
landfills, converted to energy, released as emissions, stored, and removed. There
is one row for each stand and cycle year."

descFVS_Fuels=
"<b>FVS_Fuels</b> is generated by the Fire and Fuels Extension. The table contains
fuel loads of standing trees by size classes and dead verses live, and surface fuels
by fuel class (litter, duff, and down wood size classes). There is one row for each stand and 
cycle year."

descFVS_Potfire=
"<b>FVS_Potfire</b> is generated by the Fire and Fuels Extension. The table contains 
predicted <b>potential</b> flame lengths, torching indices, crowing indices, probbility of torching, 
tree mortality, smoke production and fuel models for <i>moderate</i> and <i>severe</i> 
fire conditions. There is one row for each stand and cycle year. For the eastern FVS variants,
the table is called FVS_Potfire_East and the content differes in some ways."

descFVS_BurnReport=
"<b>FVS_BurnReport</b> is generated by the Fire and Fuels Extension. For a simlated fire,
the table contains information describing the fire conditions including moisture content
by fuel category, slope, flame length, scorch height, and the fuel models used by
the fire model."

descFVS_Mortality=
"<b>FVS_Mortality</b> is generated by the Fire and Fuels Extension. The table contains
the number of trees by species before a fire and killed by a simulated fire reported by diameter 
class. Killed basal area and volume are also reported. There is a row for every species, stand, 
and cycle inwhich there is a simulated fire."

descFVS_Down_Wood_Cov=
"<b>FVS_Down_Wood_Cov</b> is generated by the Fire and Fuels Extension. The table contains
estimates of the amount of cover (in percent) provided by stand down wood of different size
classes as hard or soft down wood. There is one row for each stand and cycle year. This table contains
the same information as FVS_Down_Wood_Vol except the units are percent cover."

descFVS_Down_Wood_Vol=
"<b>FVS_Down_Wood_Vol</b> is generated by the Fire and Fuels Extension. The table contains
estimates of the amount of volume provided by stand down wood of different size
classes as hard or soft down wood. There is one row for each stand and cycle year. This table contains
the same information as FVS_Down_Wood_Cov except the units are wood volume."

descFVS_CanProfile=
"<b>FVS_CanProfile</b> is generated by the Fire and Fuels Extension. The table contains
the amount of canopy fuel by height class. That is, there is one row for each stand, cycle
year, and height class."

descFVS_SnagSum=
"<b>FVS_SnagSum</b> is generated by the Fire and Fuels Extension. The table contains
the number of hard and soft snags by tree size class. There is one row for each stand and 
cycle year."

descFVS_SnagDet=
"<b>FVS_SnagDet</b> is generated by the Fire and Fuels Extension. The table contains
detailed snag information; there is one row for each combination of species 
and DBH class, stand, and cycle year. The information includes the height of hard and soft 
snags, there volumes, the numbers per acre, and year the tree died."

descFVS_StrClass=
"<b>FVS_StrClass</b> contains information on how many strata there are in a stand
and descriptive information on the size, species, and percent cover of the trees in 
each stratum. The stand structure classification is also reported. There is one row for each cycle
year when there is no harvest and two rows (before and after harvest) in cycles with a harvest."

descFVS_Climate=
"<b>FVS_Climate</b> is generated by Cliamte-FVS (western variants only). The table
contains the species viability scores, the number of trees and basal area, the number 
killed, the growth rate, site, and maximum density multipliers. The number of newly
established trees is also reported. There is a row for each tree species, stand, and cycle year."


descFVS_EconSummary="<b>FVS_EconSummary</b> is generated by the Econ extension of FVS. The
table contains undiscounted and discounted costs and revenues, Present Net Value, 
Internal Rate of Return, Benefit-Cost Ratio, Soil Expectation Value, and a few other
values. There is one row for each stand and cycle year. Additional Econ Extension 
keywords are required to generate useful information in this table. "

descFVS_EconHarvestValue=
"<b>FVS_EconHarvestValue</b> is generated by the Econ extension of FVS. The table 
contains the species, inside bark diameters, values, and volume of trees removed. There
is one line for each harvested tree, stand, and cycle year of harvest. Additional
Econ Extension keywords are required to generate useful information in this table."

descFVS_RD_Sum=
"<b>FVS_RD_Sum</b> is generated by the Western Root Disease Extension of FVS. The table 
contains information about the kind of root disease, the number of centers, the stand
area affected, the spread rate, number, and basal area of stumps, tree mortality, and 
percent of roots infected. There is one row for each stand and cycle year."

descFVS_RD_Det=
"<b>FVS_RD_Det</b> is generated by the Western Root Disease Extension of FVS. The 
table contains disease type, area, tree species, DBH distributions of mortality and
live trees, number of live and killed trees, and percent roots infected for 
each root disease center, stand, and cycle year."

descFVS_RD_Beetle=
"<b>FVS_RD_Beetle</b> is generated by the Western Root Disease Extension of FVS. The table 
contains information about the nubmer of trees killed by bark beetles by tree size class and
in total. There is a row for each species, for trees inside disease centers that 
are infected, for those not infected, and those outside disease centers, each stand,
and cycle year."

                                   

             