# $Id: ui.R 3389 2021-02-09 03:00:48Z mshettles521 $

FVSOnlineUI <- fixedPage(
  tags$head(tags$style(HTML(
    ".shiny-notification {height: 80px;width: 500px;position:fixed;top: calc(50% - 40px);;left: calc(50% - 250px);;}"))),
  tags$style(type="text/css", ".progress-bar {color: transparent!important}"),
  singleton(tags$head(tags$script(src = "message-handler.js"))),
  tags$style(HTML(paste0(
    ".nav>li>a {padding:3px;}",
    ".btn {padding:2px 2px;color:darkred; background-color:#eef8ff;}",
    ".form-control {padding:2px 4px; height:auto;}",
    ".form-group {margin-bottom:4px}",
    ".leaflet-popup-content-wrapper,.leaflet-popup-tip {background: rgb(255, 255, 255, .7); box-shadow: 0 3px 14px rgba(0,0,0,0.4);"
    ))),
  tags$script('
    Shiny.addCustomMessageHandler("resetFileInputHandler", function(x) {   
        var el = $("#" + x);
        el.replaceWith(el = el.clone(true));
        var id = "#" + x + "_progress";     
        $(id).css("visibility", "hidden");});'
    ),       
  tags$head(tags$script(HTML(
      'Shiny.addCustomMessageHandler("jsCode",function(message) {eval(message.code);});'))),
  fixedRow(column(width=4,offset=0,
      HTML(paste0(
             '<h4><img src="FVSlogo.png" align="middle"</img>',
             '&nbsp;Forest Vegetation Simulator</h4>'))),
    column(width=4,offset=.5,uiOutput("projectTitle")),
    column(width=2,
      tags$style(type="text/css", paste0(".shiny-progress .progress-text {", 
             "background-color: #eef8ff; color: black; ",
             "position: absolute; left: 30px;",            
             "opacity: .9; height: 35px; width: 50%;}")),
      uiOutput("contCnts")),
    column(width=2,uiOutput("serverDate"))
  ), #End of Header
  fixedRow(column(width=12,offset=0,
    tags$style(type="text/css","#topPan {background-color: rgb(227,227,255);}"),
    uiOutput("appLocked"),
    tabsetPanel(id="topPan",
      tabPanel("Runs",
        fixedRow(column(width=4,offset=0,h6(),
          tags$style(type="text/css", "#runSel { width: 100%; }"),
          selectInput("runSel","Selected run", NULL, NULL, multiple=FALSE,
                      selectize=FALSE),
          actionButton("newRun","New"),
          actionButton("reload","Reload"),
          tags$style(type="text/css", "#saveRun { color: green; }"),
          actionButton("saveRun","Save"),
          actionButton("dupRun","Duplicate"),
          modalTriggerButton("deleteRun", "#deleteRunDlg", "Delete"),
          modalDialog(id="deleteRunDlg", footer=list(
            modalTriggerButton("deleteRunDlgBtn", "#deleteRunDlg", "Yes"),
              tags$button(type = "button", class = "btn btn-primary", 
               'data-dismiss' = "modal", "Cancel"))),
          h6(),
          tags$style(type="text/css", "#title { width: 90%; }"),
          textInput("title", "Run title", ""), 
          # all the select objects
          tags$style(type="text/css", "select { width: 100%; }"),
          h6(),
          tags$style(type="text/css", "#simCont { width: 100%; height: 400px;}"),
          myRadioGroup("simContType", "Run Contents ", 
                c("Full run","Just groups")),
          selectInput("simCont",NULL, NULL, NULL, multiple=TRUE,
                      selectize=FALSE),
          actionButton("editSel","Edit"),
          actionButton("mkfree","Change to freeform"),
          actionButton("cutCmp","Cut/Delete"),
          actionButton("copyCmp","Copy"),h6(),
          actionButton("paste","Paste item selected below"),
          selectInput("selpaste","Components available to paste", NULL, 
                      NULL, multiple=FALSE, selectize=FALSE), 
          myInlineTextInput("searchString", "Find stand:", value = "", size="25%"),
          actionButton("searchNext","Find")
        ),
        column(width=8,offset=.2,
          tags$style(type="text/css","#rightPan {background-color: rgb(227,255,227);}"),
          tabsetPanel(id = "rightPan",
            tabPanel("Stands",
              selectInput("inTabs","Inventory Data Tables", NULL, NULL, 
                        multiple=FALSE, selectize=FALSE),
              selectInput("inVars","Variants", NULL, NULL, 
                        multiple=FALSE, selectize=FALSE),
              selectInput("inGrps","Groups", NULL, NULL, 
                        multiple=TRUE, selectize=FALSE, size=6),
              myRadioGroup("inAnyAll", "Stands must be in any or all selected groups ", 
                c("Any","All")),               
              tags$style(type="text/css", "#inStds { height: 300px;}"),
              selectInput("inStds", NULL, NULL, NULL, 
                        multiple=TRUE, selectize=FALSE),
              uiOutput("stdSelMsg"),
              myInlineTextInput("inReps", "Number of replicates of each added stand ", value = "1", size="5%"),            
              myInlineTextInput("inRwts", "Relative weights of each replicate ", value = "1", size="20%"), 
              h6(),
              actionButton("inAdd",   "Add selected stands"),
              actionButton("inAddGrp","Add stands in selected groups"), 
              h6(),
              myInlineTextInput("inStdFind", "Find stand(s):", value = "", size="25%"),
              actionButton("inStdFindBut","Find")
            ), 
            tabPanel("Time",
              textInput("startyr",  "Common starting year", ""), 
              textInput("endyr",    "Common ending year",   ""),                                        
              textInput("cyclelen", "Growth and reporting interval (years)",  ""), 
              tags$style(type="text/css", "#cycleat { width: 90%; }"),
              textInput("cycleat", "Additional output reporting years", ""),
              h4("Projection Timing Summary"),
              HTML(paste0('FVS will project your data, beginning from the year of inventory, to the common',
                   ' starting year of ',htmlOutput("srtYr", inline=TRUE),' for all stands. Thereafter, FVS',
                   ' will grow the stand, and provide output, in intervals of ',htmlOutput("cyLen", inline=TRUE),
                   ' years, with the simulation ending at the common ending year, for all stands, of ',
                   htmlOutput("eYr", inline=TRUE),
                   '. You will receive output for the additional year(s): ',htmlOutput("cyAt", inline=TRUE)))
            ),
            tabPanel("Components",          
              tags$style(type="text/css","#compTabSet {background-color: rgb(255,227,227);}"),     
              tabsetPanel(id = "compTabSet",
                tabPanel("Management",
                  selectInput ("addMgmtCats","Categories",NULL,
                               multiple=FALSE,selectize=FALSE),
                  selectInput("addMgmtCmps","Components",NULL,
                               multiple=FALSE,selectize=FALSE)
                  ),
               tabPanel("Modifiers",                    
                 selectInput("addModCats","Categories",NULL,
                             multiple=FALSE,selectize=FALSE),
                 selectInput("addModCmps","Components",NULL,
                             multiple=FALSE,selectize=FALSE)),
               tabPanel("Event Monitor",h6(),
                 selectInput("addEvCmps",NULL,NULL,multiple=FALSE,selectize=FALSE)),
               tabPanel("Economic",h6()),
               tabPanel("Keywords",
                 h5("Note: Avoid direct use of keywords when possible."),
                 selectInput("addKeyExt","Extensions",NULL,
                             multiple=FALSE,selectize=FALSE),
                 selectInput("addKeyWds","Keywords",NULL,
                             multiple=FALSE,selectize=FALSE)),
               tabPanel("Editor",
                 h5(),
                 fileInput("kcpUpload",
                           "Upload an existing Keyword component file (KCP), or Keyword component archive (FVS_kcps.Rdata)",
                           width="90%"),
                 selectInput("kcpSel","Existing component collection", NULL, 
                            NULL, multiple=FALSE,selectize=FALSE,width="65%"),h6(),
                 actionButton("kcpNew","New"),
                 actionButton("kcpAppend","Append selected component from run"),
                 tags$style(type="text/css", "#kcpSaveInRun {color:green;}"),
                 actionButton("kcpSaveInRun","Save in run"),
                 tags$style(type="text/css", "#kcpSaveCmps {color:green;}"),
                 actionButton("kcpSaveCmps","Save in component collection"),
                 tags$style(type="text/css", "#kcpDelete { color: red; }"),
                 actionButton("kcpDelete","Delete"),
                 tags$style(type="text/css", "#kcpDownload { color: black; }"),
                 downloadButton("kcpDownload","Download (KCP)"),
                 h6(),
                 tags$style(type="text/css", "#kcpTitle { width: 60%; }"),
                 myInlineTextInput("kcpTitle", "Component Title: ", value = "", size="65%"),h6(),      
                 tags$style(type="text/css", 
                    "#kcpCols{font-family:monospace;font-size:90%;width:80%;}"), 
                 tags$p(id="kcpCols", 
                     HTML(paste0("&nbsp;",paste0("....+....",1:8,collapse="")))),
                 tags$style(type="text/css", 
                    "#kcpEdit{font-family:monospace;font-size:90%;width:95%;}"), 
                 tags$textarea(id="kcpEdit", rows=15),h6())),
             uiOutput("titleBuild"),
             uiOutput("condBuild"),
             uiOutput("cmdBuild"),
             uiOutput("cmdBuildDesc"),h5()
           ), #End Components
           tabPanel("Select Outputs",
             h4("Select outputs"),
             HTML(paste0("Note that all outputs are put in output database except for the SVS data.<br>",
                  "FVS_Cases, FVS_Summary, FVS_Compute, and mistletoe (FVS_DM_Stnd_Sum,",
                  "FVS_DM_Spp_Sum) are always produced.")),h6(),                       
             fixedRow(
               column(width=2,style="padding-top:6px;",
                 checkboxGroupInput("autoSVS",NULL,choices=list(
                   "SVS:"="autoSVS"),width="100%",inline=TRUE)),
               column(width=5,style="padding-top:6px;",
                   myRadioGroup("svsPlotShape","Plot shape",list("Round","Square"),
                       selected="Round",labelstyle="font-weight:normal")),
               column(width=5,
                   myInlineNumericInput("svsNFire","Images per fire:", value="4", min="1", max="8", 
                                        step="1",size=15,labelstyle="font-weight:normal;"))),
             checkboxGroupInput("autoOut",NULL,choices=list(
                 "Tree lists (FVS_Treelist, FVS_CutList (StdStk-stand and stock))"="autoTreelists",
                 "Carbon and fuels (FVS_Carbon, FVS_Consumption, FVS_Hrv_Carbon, FVS_Fuels)"="autoCarbon",
                 "Fire and mortality (FVS_Potfire, FVS_BurnReport, FVS_Mortality)"="autoFire",
                 "Snags and down wood (FVS_SnagSum, FVS_Down_Wood_Cov, FVS_Down_Wood_Vol)"="autoDead",
                 "FFE canopy profile (FVS_CanProfile)"="autoCanProfile",          
                 "FFE detailed snag (FVS_SnagDet)"="autoSnagDet",  
                 "Stand structure (FVS_StrClass)"="autoStrClass",
                 "Calibration stats (FVS_CalibStats)"="autoCalibStats",  
                 "Climate-FVS (FVS_Climate)"="autoClimate",                                    
                 "Economics (FVS_EconSummary, FVS_EconHarvestValue)"="autoEcon",
                 "Mistletoe detail by tree size (FVS_DM_Sz_Sum)"="autoDM_Sz_Sum",  
                 "Western Root Disease summary (FVS_RD_Sum)"="autoRD_Sum",  
                 "Western Root Disease details (FVS_RD_Det)"="autoRD_Det",  
                 "Western Root Disease bark beetles (FVS_RD_Beetle)"="autoRD_Beetle",
                 "Inventory Statistics (FVS_Stats_Species, FVS_Stats_Stand)"="autoInvStats",
                 paste0("Regeneration (All Variants: FVS_Regen_Sprouts, FVS_Regen_SitePrep, FVS_Regen_Tally.",
                        "AK, EM, KT, IE, and CI variants also get: FVS_Regen_HabType, FVS_Regen_Ingrowth))"="autoRegen",
                 "Include text outputs in the main output file (otherwise many are suppressed)"="autoDelOTab"  
                 ),width="100%",inline=FALSE)),
            selectInput("tabDescSel","Describe tables",choices=list(),
                 multiple=FALSE,selectize=FALSE),
                 h5(),uiOutput("tabDesc")
          ), #End select outputs
          tabPanel(title=htmlOutput("contChange"),   # Make a Runs
            fixedRow(
              column(width=3,
                tags$style(type="text/css", "#defMgmtID { width: 65px; }"),
                textInput("defMgmtID","MgmtID (4 chars)",""),
                radioButtons("runwaitback", NULL, 
                  c("Wait for run","Run in background")),
                actionButton("saveandrun","Save and Run"),
                h6(),
                downloadButton("dlFVSRunout","FVS Main Output File"),
                h4()
              ),
              column(width=9,
                customRunElements
              )
            ),
            uiOutput("uiRunPlot"),
            uiOutput("uiErrorScan"),
            selectInput("bkgRuns", "Background run status", 
              choices  = list(), size=4, width = "95%", selected = NULL, selectize=FALSE),
            actionButton("bkgKill","Kill selected background run"),
            actionButton("bkgRefresh","Refresh list")
          ) #END Make Runs 
        ) #END right panel 
      ) ) ), #End column END of Runs item in top panel 
      tabPanel("View Outputs",
        fixedRow(column(width=4,offset=0,
          tags$style(type="text/css","#leftPan {background-color: rgb(255,227,227);}"),
          tabsetPanel(id="leftPan", 
            tabPanel("Load", 
              myRadioGroup("spCodes","Species codes",
                  c("FVS"="FVS","FIA"="FIA","Plants"="PLANTS"),selected = "PLANTS"),
              selectInput("runs", "Runs to consider", 
                choices  = list(), size=4,
                selected = NULL, multiple = TRUE, selectize=FALSE),
              tags$style(type="text/css", "#sdskwdbh { width: 30%;}"),
              tags$style(type="text/css", "#sdskldbh { width: 50%;}"),
              fixedRow(
                column(width=7,
                  numericInput("sdskwdbh", "DBH class size", 4, min=1, 
                                max=20,step=1)),
                column(width=5,
                  numericInput("sdskldbh", "Large DBH", 48, min=4, 
                                max=100,step=1))),
              actionButton("bldstdsk","Rebuild StdStk"), 
              selectInput("selectdbtables", "Database tables to consider", 
                choices  = list(), size=8,
                selected = NULL, multiple = TRUE, selectize=FALSE),
              selectInput("selectdbvars", "Database variables to consider", 
                choices  = list(), size=20,
                selected = NULL, multiple = TRUE, selectize=FALSE)
            ),
            tabPanel("Explore", 
              selectInput("stdtitle", "Select run titles", size=4,
                  choices  = list("None loaded"), width="100%",
                  selected = NULL, multiple = TRUE, selectize=FALSE),
              selectInput("stdgroups", "Groups", size=4,
                  choices  = list("None loaded"), width="100%",
                  selected = NULL, multiple = TRUE, selectize=FALSE),
              fixedRow(column(width=8,
                  selectInput("stdid", "Stands", size=6,
                    choices  = list("None loaded"), 
                    selected = NULL, multiple = TRUE, selectize=FALSE)),
                column(width=4,
                  selectInput("mgmid", "MgmtIDs", size=6, 
                    choices  = list("None loaded"), 
                    selected = NULL, multiple = TRUE, selectize=FALSE))),
              fixedRow(column(width=4,
                  selectInput("year", "Years", size=6,  
                      choices  = list("None loaded"), 
                      selected = NULL, multiple = TRUE, selectize=FALSE)),           
                column(width=4,
                  selectInput("species", "Species", size=6, 
                    choices  = list("None loaded"), 
                    selected = NULL, multiple = TRUE, selectize=FALSE)),
                column(width=4,
                  selectInput("dbhclass", "DBHClasses", size=6, 
                    choices  = list("None loaded"), 
                    selected = NULL, multiple = TRUE, selectize=FALSE))),
                HTML(paste0("<b>",'Databse table(s) selected: ',"</b>",htmlOutput("tbSel", inline=TRUE))),
              checkboxGroupInput("browsevars","Select variables",
                  choices = list("None"),selected = NULL,inline=TRUE)
            ),
            tabPanel("Custom Query",
              selectInput("sqlSel","SQL queries (run on FVSOut.db (SQLite3))", 
                NULL, NULL, multiple=FALSE,selectize=FALSE,width="100%"),
              textInput("sqlTitle", "Query name: ", value = "", width="100%"),
              h6(),
              tags$style(type="text/css", 
                    "#sqlQuery{font-family:monospace;font-size:90%;width:100%;}"), 
              tags$textarea(id="sqlQuery",rows=15,""),
              h6(),
              tags$style(type="text/css", "#sqlRunQuery { color: green; }"),
              actionButton("sqlRunQuery","Run query"),
              actionButton("sqlSave","Save"),
              actionButton("sqlNew","New"),
              tags$style(type="text/css", "#sqlDelete { color: red; }"),
              actionButton("sqlDelete","Delete"),
              h6("Output from query"),
              tags$style(type="text/css", 
                    "#sqlOutput{font-family:monospace;font-size:90%;width:100%;}"), 
              tags$textarea(id="sqlOutput",rows=5,""),
              tags$p(id="sqlInstructions", 
                  HTML(paste0('Use "<b>;</b>" to separate SQL statements.<br>',
                    'The last statement that results in a table being returned ',
                    'defines the end of the sequence. That table is ',
                    'used in <b>Tables</b> and <b>Graphs</b>')))
        ) ) ), #END of outputleft pan
        column(width=8,offset=.2,
        tags$style(type="text/css","#outputRightPan {background-color: rgb(227,255,227);}"),
        conditionalPanel("input.leftPan != 'Load'", 
          tabsetPanel(id="outputRightPan",tabPanel("Tables",
            fixedRow(
              column(width=3,
                selectInput("pivVar", choices=list("None"), 
                  "Convert to columns", selectize=FALSE)),
              column(width=3,
                selectInput("dispVar", choices=list("None"), 
                  "Variable to display", selectize=FALSE)),         
              column(width=4,
                   downloadButton("dlRenderData","Download table"),
                   myRadioGroup("dlRDType","Type", c(".xlsx",".csv"))),
            tags$style(type="text/css","#tableLimitMsg{color:darkred;}"),          
            fixedRow(column(width=12,textOutput("tableLimitMsg"))),
            fixedRow(column(width=12,rHandsontableOutput("table")))
          ) ),
          tabPanel("Graphs",
            fixedRow(
              column(width=4,
                selectInput("OPsettings", choices=list(), 
                  "Apply saved settings", selectize=FALSE)),
              column(width=1,
                h1(),actionButton("OPredo","Redo")),
              column(width=4,
                textInput("OPname", "Setting name", value = "", width="100%")),
              column(width=3,
                actionButton("OPsave","Save current settings"),
                actionButton("OPdel","Delete current settings"))),
            uiOutput("OPmessage"),    
            div(style="height:1px;width:100%;background-color:lightgray;"),
            fixedRow(
              column(width=7,
                myRadioGroup("plotType","Type", 
                  c("line","scat","box","bar","DMD","StkCht"))),
              column(width=3,
                myRadioGroup("colBW","", c("Color","B&W")))),
            fixedRow(
              column(width=3,
                selectInput("yaxis", "Y-axis", choices  = list("Year"), 
                    selected = NULL, multiple = TRUE, selectize=FALSE)),
              column(width=3,
                selectInput("xaxis", "X-axis", 
                  choices  = list("None"), selected = NULL, selectize=FALSE),
                selectInput("hfacet", "Horizontal facet",
                    choices = list("None","StandID","MgmtID","Year","Species"),
                    selected="None", selectize=FALSE)),
              column(width=6,
                textInput("ptitle", "Title", value = ""),              
                textInput("xlabel", "X-label", value = ""))),
            fixedRow(
              column(width=3,
                selectInput("vfacet", "Vertical facet",
                    choices = list("None","StandID","MgmtID","Year","Species"),
                    selected="None", selectize=FALSE)),
              column(width=3,
                selectInput("pltby", "Plot-by code",
                    choices = list("None","StandID","MgmtID","Year","Species"),
                    selected="None", selectize=FALSE)),
              column(width=6,
                textInput("ylabel", "Y-label", value = ""))),
            fixedRow(
              column(width=3,
                myInlineTextInput("width",  "Width (in)", value = 4, size=5)),
              column(width=3,
                myInlineTextInput("height", "Height (in)", value = 3, size=5)), 
              column(width=6,
                myRadioGroup("moreControls","More controls", c("Hide","Show")))),
             fixedRow(column(width=12,conditionalPanel("input.moreControls == 'Show'",
               fixedRow(
                 column(width=2,               
                   colourInput("color1",  "Color 1", showColour="both", value = cbbPalette[1]),
                   colourInput("color2",  "Color 2", showColour="both", value = cbbPalette[2]),
                   colourInput("color3",  "Color 3", showColour="both", value = cbbPalette[3])),
                 column(width=2,                                         
                   colourInput("color4",  "Color 4", showColour="both", value = cbbPalette[4]),
                   colourInput("color5",  "Color 5", showColour="both", value = cbbPalette[5]),
                   colourInput("color6",  "Color 6", showColour="both", value = cbbPalette[6])),
                 column(width=2,                                         
                   colourInput("color7",  "Color 7", showColour="both", value = cbbPalette[7]),
                   colourInput("color8",  "Color 8", showColour="both", value = cbbPalette[8]),
                   colourInput("color9",  "Color 9", showColour="both", value = cbbPalette[9])),
                 column(width=2,
                   colourInput("color10", "Color 10", showColour="both", value = cbbPalette[10]),
                   colourInput("color11", "Color 11", showColour="both", value = cbbPalette[11]),
                   colourInput("color12", "Color 12", showColour="both", value = cbbPalette[12])),
                 column(width=2,                                           
                   colourInput("color13", "Color 13", showColour="both", value = cbbPalette[13]),
                   colourInput("color14", "Color 14", showColour="both", value = cbbPalette[14]),
                   colourInput("color15", "Color 15", showColour="both", value = cbbPalette[15])),
                 column(width=2,                                         
                   colourInput("color16", "Color 16", showColour="both", value = cbbPalette[16]),
                   colourInput("color17", "Color 17", showColour="both", value = cbbPalette[17]),
                   colourInput("color18", "Color 18", showColour="both", value = cbbPalette[18]))),
               fixedRow(
                 column(width=3, 
                   radioButtons("res","Resolution (ppi)",c("150","300","600"))),
                 column(width=4,
                 sliderInput("transparency", "Transparency", 0, 1, .3, step = .01)),
                 column(width=1),
                 column(width=2,fixedRow(textInput("YLimMin","Min Y limit:")),
                                fixedRow(textInput("YLimMax","Max Y limit:"))),
                 column(width=2,fixedRow(textInput("XLimMin","Min X limit:")), 
                                fixedRow(textInput("XLimMax","Max X limit:")))),
               fixedRow(
                 column(width=6,
                   myRadioGroup("YlabRot","Rotate Y-Labels (degrees)",
                      c("0"="0","45"="45","90"="90"))),
                 column(width=6,
                   myRadioGroup("XlabRot","Rotate X-Labels (degrees)",
                      c("0"="0","45"="45","90"="90")))),
               fixedRow(
                 column(width=6,
                   myRadioGroup("barPlace","Bars",
                      c("Stacked"="stack","Side-by-side"="dodge"))),
                 column(width=6,
                   myRadioGroup("legendPlace","Legend",
                      c("R"="right","Bot"="bottom","L"="left",
                        "Top"="top","None"="none")))),
               fixedRow(
                 column(width=6,
                   myRadioGroup("YTrans","Transform Y",
                      c("identity"="identity","log10"="log10"))),
                 column(width=6,
                   myRadioGroup("XTrans","Transform X",
                      c("identity"="identity","log10"="log10")))),
               fixedRow(
                 column(width=6,
                   myRadioGroup("facetWrap","Automatic facet wrap",
                      c("On"="On","Off"="Off")))),
               fixedRow(
                 column(width=12,
                   myInlineTextInput("SDIvals", 
                    "SDI values for Density Mgmt Diagram (DMG):",
                     "35%,60%,600", size=25))),
               fixedRow(
                 column(width=6,
                   myRadioGroup("YUnits","DMG Y-Units:",
                      c("Tpa"="Tpa","QMD"="QMD"),selected="Tpa")),
                 column(width=6,
                   myRadioGroup("XUnits","DMG X-Units",
                      c("Tpa"="Tpa","QMD"="QMD"),selected="QMD"))),
               fixedRow(
                 column(width=12,
                   myInlineTextInput("StkChtvals", 
                    "Full stocking percentages for Stocking Chart (StkCht):",
                     "30%,55%,100%,110%", size=25))))
            )),
            fixedRow(column(width=6, 
              tags$style(type="text/css","#plotMessage{color:darkred;}"),          
              textOutput("plotMessage")),
                column(width=6,h6(),actionButton("copyplot","Copy plot to clipboard"))),
            fixedRow(column(width=12,plotOutput(outputId="outplot")))
          ) #END Graphs
        ) ), #END Conditional pan 
        conditionalPanel("input.leftPan == 'Load'",
          fixedRow(
            column(width=6,                 
              tabsetPanel(id="describe",selectInput("tabDescSel2","Describe tables",
                choices=list(),multiple=FALSE,selectize=FALSE)))),
            h5(),uiOutput("tabDesc2"))
      ) ) ), # END View Outputs
      tabPanel("SVS3d",
        h6(),
        fixedRow(
          column(width=6,offset=0,         
            fixedRow(
              column(width=8,offset=0,
                checkboxGroupInput("SVSdraw1",label=NULL,width="100%",inline=TRUE,choices=
                  list("Subplots"="subplots","Range poles"="rangePoles","Fire"="fireLine",
                    "Down trees"="downTrees"),selected=c("subplots","rangePoles",
                    "fireLine","downTrees")),
                selectInput(inputId="SVSRunList1",label="Select run", choices=NULL, 
                   multiple=FALSE, selectize=FALSE, width="99%")),
              column(width=4,offset=0, 
                colourInput(inputId="svsPlotColor1",label="Plot color", showColour="both", 
                            value = "#C5FAC6"),
                actionButton(inputId="svsCopy1","Snapshot to clipboard"))),
            selectInput(inputId="SVSImgList1",label="Select SVS image", choices=NULL, 
              multiple=FALSE, selectize=FALSE, width="99%"),
# needed for the quick images.
#            fixedRow(
#              column(width=6,offset=0,HTML('<img id="SVSImg1Top"  alt="Top View"  width="200" height="200"</img>')),
#              column(width=6,offset=0,HTML('<img id="SVSImg1Side" alt="Side View" width="200" height="200"</img>'))),
            rglwidgetOutput('SVSImg1',width = "500px", height = "500px")),                                        
        column(width=6,offset=0,
            fixedRow(
              column(width=8,offset=0,
                checkboxGroupInput("SVSdraw2",label=NULL,width="100%",inline=TRUE,choices=
                  list("Subplots"="subplots","Range poles"="rangePoles","Fire"="fireLine",
                    "Down trees"="downTrees"),selected=c("subplots","rangePoles",
                    "fireLine","downTrees")),
                selectInput(inputId="SVSRunList2",label="Select run", choices=NULL, 
                   multiple=FALSE, selectize=FALSE, width="99%")),
              column(width=4,offset=0, 
                colourInput(inputId="svsPlotColor2",label="Plot color", showColour="both", 
                            value = "#C5FAC6"),
                actionButton(inputId="svsCopy2","Snapshot to clipboard"))),
            selectInput(inputId="SVSImgList2",label="Select SVS image", choices=NULL, 
              multiple=FALSE, selectize=FALSE, width="99%"),
# needed for the quick images.
#            fixedRow(
#              column(width=6,offset=0,HTML('<img id="SVSImg2Top"  alt="Top View"  width="200" height="200"</img>')),
#              column(width=6,offset=0,HTML('<img id="SVSImg2Side" alt="Side View" width="200" height="200"</img>'))),
            rglwidgetOutput('SVSImg2',width = "500px", height = "500px"))                                        
      )), #END SVS3d

      tabPanel("Maps",
        h6(),
        fixedRow(
        column(width=3,offset=0,
          selectInput(inputId="mapDsRunList",label="Select Run", choices=NULL, 
             multiple=FALSE, selectize=FALSE, width="99%")),
        column(width=2,offset=0,
          selectInput(inputId="mapDsTable",label="Output Table", choices=NULL, 
             multiple=FALSE, selectize=FALSE, width="99%")),
        column(width=1,offset=0,HTML("<b>Variables</b>")),
        column(width=2,offset=0,
          selectInput(inputId="mapDsVar",label=NULL, choices=NULL, 
             multiple=TRUE, selectize=FALSE, width="99%")),
        column(width=2,offset=0,
           radioButtons("mapDsType","Display", choices=list("table","graph"))),            
        column(width=2,offset=0,
          selectInput(inputId="mapDsProvider",label="Base map", 
            choices=list("Google Hybrid"="s,h","Google Satellite"="s",
                         "Google Streets"="m","Google Terrain"="p"),
            multiple=FALSE, selectize=FALSE, width="95%"))
         ), 
         fixedRow(column(width=12,offset=0,
           textOutput("leafletMessage"),
           leafletOutput("leafletMap",height="800px",width="100%")))
      ), #END Maps
      tabPanel("Import Input Data", 
        fixedRow(column(width=12,offset=0,
          tags$style(type="text/css","#inputDBPan {background-color: rgb(255,227,227);}"),
          tabsetPanel(id="inputDBPan", 
            tabPanel("Upload inventory database", 
              h6(),
              fileInput("uploadNewDB",paste0("Step 1: Upload FVS-Ready database ",
                        "(.accdb, .mdb, .db (SQLite3), .sqlite, .xlsx, or .zip that contains one of these)"),
                        width="90%"),
              tags$style(type="text/css","#step1ActionMsg{color:darkred;}"), 
              uiOutput("step1ActionMsg"),
              h6(),
              p(strong("Step 2: Following upload, you must do one of the following")),
              tags$style(type="text/css","#installNewDB{font-size: 120%; color:green;}"),
              tags$style(type="text/css","#addNewDB{font-size: 120%; color:green;}"),
              actionButton("installNewDB","Install uploaded database"),
              actionButton("addNewDB","Add new database to existing database"),
              tags$style(type="text/css","#step2ActionMsg{color:darkred;}"), 
              uiOutput("step2ActionMsg"),
              h5("Other options"),
              actionButton("installTrainDB","Install training data (inventory and map data)"),
              h6(),
              actionButton("installEmptyDB","Install blank database"),h6()
            ),
            tabPanel("View and edit existing tables",        
              fixedRow(column(width=3,offset=0,
                  h6(),
                  myRadioGroup("mode", "Mode ", c("Edit","New rows")),
                  myInlineTextInput("disprows",  "Number display rows", value = 20, size=5),
                  selectInput("editSelDBtabs", label="Table to process",
                        choices  = list(), 
                        selected = NULL, multiple = FALSE, selectize=FALSE),
                  selectInput("editSelDBvars", "Variables to consider", 
                      choices  = list(), size=10,
                      selected = NULL, multiple = TRUE, selectize=FALSE),
                  uiOutput("stdSel"),
                  myInlineTextInput("editStandSearch", "Find stand:", value = "", size="25%"),h6(),
                  actionButton("clearTable","Remove all rows and commit"),h6(),
                  actionButton("commitChanges","Commit edits or new rows")),
                column(width=9,offset=0,
                  h6(),uiOutput("navRows"),
                  h6(),rHandsontableOutput("tbl"),
                  textOutput("actionMsg"))),
              fixedRow(column(width=12,offset=0,h6(),uiOutput("inputTabDesc")))
            ),              
            tabPanel("Upload Map data", 
              h4("Upload a stand layer to use in the Maps feature."),       
              h5("Note: Only spatial data found to have corresponding inventory data are stored (so load it first)."),       
              fileInput("mapUpload","Step 1: Upload polygon or point data (.zip that contains spatial data)",
                      width="90%"), h6(),
              selectInput("mapUpLayers", label="Layer",
                choices  = list(), selected = NULL, multiple = FALSE, selectize=FALSE),
              selectInput("mapUpIDMatch", label="Variable that matches StandID",
                choices  = list(), selected = NULL, multiple = FALSE, selectize=FALSE),
              selectInput("mapUpSelectEPSG", label="Projection library (abridged)",
                choices  = list(), selected = NULL, multiple = FALSE, selectize=FALSE),
              textInput("mapUpProjection", label="proj4 projection string",width="70%"),
              actionButton("mapUpSetPrj","Set/Reset proj4 projection (does not reproject uploaded data)"),h6(),
               p(strong("Step 2: Do one of the following:")),  
              tags$style(type="text/css","#mapUpSave{font-size: 120%; color:green;}"),
              tags$style(type="text/css","#mapUpAdd{font-size: 120%; color:green;}"),
              actionButton("mapUpSave","Install imported spatial data"),           
              actionButton("mapUpAdd", "Add imported spatial to existing data"),h6(),
              h5("Another option"),
              actionButton("installTrainDB2","Install training data (inventory and map data)"),   
              tags$style(type="text/css","#mapActionMsg{color:darkred;}"), 
              uiOutput("mapActionMsg")
            ),
            tabPanel("Append .csv data to existing tables", 
              h4(),             
               selectInput("uploadSelDBtabs", label="Table to process",
                choices  = list(), selected = NULL, multiple = FALSE, selectize=FALSE),
              fileInput("uploadStdTree",
                       'Upload .csv file and append to "Table to process"',
                        width="90%"), 
              tags$style(type="text/css","#uploadActionMsg{color:darkred;}"), 
              uiOutput("uploadActionMsg")     
            ),
            tabPanel("Upload Climate-FVS data", 
              h4(),             
              fileInput("climateFVSUpload",
                        "Upload and commit Climate-FVS data; (FVSClimAttrs.csv or answers.zip)",
                        width="90%"),                                                                            
              tags$style(type="text/css","#uploadActionMsg{color:darkred;}"), 
              uiOutput("uploadClimActionMsg")     
            ) #END tabPanel
          ) #END tabsetPanel
      ) ) ), #END END Import input data
      tabPanel("Project Tools",
        tags$style(type="text/css","#toolsPan {background-color: rgb(255,227,227);}"),
        tabsetPanel(id="toolsPan",        
          tabPanel("Import runs and other items",
            HTML(paste0('<p style="font-size:17px;color:darkgreen"><br><b>Step 1:</b> ',         
              'Choose a source of items to be imported. The source can be another ',               
              'of your projects or you can upload a zip file that contains runs and ',
              'other project items. If you pick a project, the items that can be imported ',
              'are shown in the list boxes below and if you upload a zip file, those items ',
              'are in the list boxes. The zip file can ',
              'be one created using the <i>Downloads</i> tab or a project backup created ',
              'using the <i>Manage projects</i> tab.<br><br>Note: If you import runs ',
              'that were created using different inventory data than what you have in this project, ',
              'those data will need to be imported to run the imported runs.</p>')),h3(),                            
            fileInput("uploadRunsRdat","Upload source .zip file",width="90%"),
            selectInput(inputId="impPrjSource", 
                 label="Select an existing project as a source", multiple=FALSE,
                 choices = list(), selectize=FALSE),                 
            HTML(paste0('<p style="font-size:17px;color:darkgreen"><br><b>Step 2:</b> ',
              'Import items shown below into your current project. Note that ',
              'it is a good practice to make a project backup before importing ',
              'the input FVS_Data base or the Spatial data.</p>')),
            h3(),
            uiOutput("selectedSourceMsg"), 
            fixedRow(column(width=4,offset=0,
              selectInput(inputId="impRuns", label="Select a run to import", multiple=FALSE, 
                    choices=list(),selectize=FALSE)),
                    column(width=1,offset=0,
                      h3(),actionButton(inputId="doImpRuns", label="Import")),    
                    column(width=7,offset=0,h3(),uiOutput("impRunsMsg"))), 
            fixedRow(column(width=4,offset=0,h6(),              
              selectInput(inputId="impCustomCmps", label="Select a custom component (.kcp)",  
                    choices=list(),multiple=FALSE, selectize=FALSE)),
                    column(width=1,offset=0,
                      h3(),actionButton(inputId="doImpCustomCmps", label="Import")),    
                    column(width=7,offset=0,h3(),uiOutput("impCustomCmpsMsg"))),
            fixedRow(column(width=4,offset=0,h6(), 
              selectInput(inputId="impGraphSettings", label="Select a graph setting", 
                    choices=list(),multiple=FALSE,selectize=FALSE)),
                    column(width=1,offset=0,
                      h3(),actionButton(inputId="doImpGraphSettings", label="Import")),    
                    column(width=7,offset=0,h3(),uiOutput("impGraphSettingsMsg"))), 
            fixedRow(column(width=4,offset=0,h6(),
              selectInput(inputId="impCustomQueries", label="Select a custom query", 
                    choices=list(),multiple=FALSE,selectize=FALSE)),
                    column(width=1,offset=0,
                      h3(),actionButton(inputId="doImpCustomQueries", label="Import")),    
                    column(width=7,offset=0,h3(),uiOutput("impCustomQueriesMsg"))), 
            fixedRow(column(width=5,offset=0,h6(),list(
              modalTriggerButton("impFVS_Data", "#impFVS_DataDlg", 
                "Import FVS_Data.db"),
              modalDialog(id="impFVS_DataDlg", footer=
                modalTriggerButton("impFVS_DataDlgBtn", "#impFVS_DataDlg", 
                  "Yes"), tags$button(type = "button", class = "btn btn-primary", 
                  'data-dismiss' = "modal", "Cancel")))),
                  column(width=7,offset=0,h5(),uiOutput("impFVS_DataMsg"),h3())),                    
            fixedRow(column(width=5,offset=0,h6(),list(
              modalTriggerButton("impSpatialData", "#impSpatialDataDlg", 
                "Import the Spatial Data"),
              modalDialog(id="impSpatialDataDlg", footer=
                modalTriggerButton("impSpatialDataDlgBtn", "#impSpatialDataDlg", 
                  "Yes"), tags$button(type = "button", class = "btn btn-primary", 
                  'data-dismiss' = "modal", "Cancel")))),
                  column(width=7,offset=0,h5(),uiOutput("impSpatialDataMsg"),h3()))                    
          ), #END oF Import items
          tabPanel("Manage project",   
              h4(),h4("Start another project"), 
              selectInput("PrjSelect", "Select project", multiple=FALSE,
                 choices = list(), selectize=FALSE),       
              actionButton("PrjOpen","Open selected project"),h4(),
              h4("Create a new project"),
              textInput("PrjNewTitle", "New project title", ""), 
              actionButton("PrjNew","Make new project"),
            h4("Delete outputs in current project"),
            list(
              modalTriggerButton("deleteAllOutputs", "#deleteAllOutputsDlg", 
                "Delete ALL outputs in current project"),
              modalDialog(id="deleteAllOutputsDlg", footer=list(
                modalTriggerButton("deleteAllOutputsDlgBtn", "#deleteAllOutputsDlg", 
                  "Yes"),
                tags$button(type = "button", class = "btn btn-primary", 
                  'data-dismiss' = "modal", "Cancel")))
            ),                      
            h4(),h4("Delete runs in current project"),
            list(
              modalTriggerButton("deleteAllRuns", "#deleteAllRunsDlg", 
                "Delete ALL runs and related outputs in current project"),
              modalDialog(id="deleteAllRunsDlg", footer=list(
                modalTriggerButton("deleteAllRunsDlgBtn", "#deleteAllRunsDlg", 
                  "Yes"),tags$button(type = "button", class = "btn btn-primary", 
                  'data-dismiss' = "modal", "Cancel")))
            ),  
            h4(),h4("Make new project backup file"),
            radioButtons("prjBckCnts",NULL,width="50%",choices=
               list("Project files only"="projOnly",
                    "Project files and FVS software"="projFVS"),
                    selected="projOnly"),
            actionButton("mkZipBackup","Make a project backup zip file"),                          
            h4("Manage current project backup files"),
            selectInput("pickBackup", "Select backup to process", multiple=FALSE,
               choices = list(), selectize=FALSE),
            actionButton("delZipBackup","Delete backup"),
            downloadButton("dlPrjBackup","Download backup"),
            tags$style(type="text/css","#restorePrjBackupDlg{color:darkred;font-size:150%;width:100%;}"),
            list(
              modalTriggerButton("restorePrjBackup", "#restorePrjBackupDlg", 
                "Restore from backup"),
              modalDialog(id="restorePrjBackupDlg", footer=list(
                modalTriggerButton("restorePrjBackupDlgBtnA", "#restorePrjBackupDlg", 
                  htmlOutput("btnA", inline=TRUE)),
                modalTriggerButton("restorePrjBackupDlgBtnB", "#restorePrjBackupDlg", 
                  htmlOutput("btnB", inline=TRUE)),
                modalTriggerButton("restorePrjBackupDlgBtnC", "#restorePrjBackupDlg", 
                  "Cancel"))) 
              ),
            h4(),
            h4("Upload existing project backup file into current project"),
            fileInput("upZipBackup","Upload project backup zip file",width="30%"),
            uiOutput("delPrjActionMsg"),
            h4("Delete entire project"),
            selectInput("PrjDelSelect", "Select project to delete", multiple=FALSE,
                        choices = list(), selectize=FALSE),                                        
            list(modalTriggerButton("PrjDelete", "#PrjDeleteDlg", "Delete project"),
                 modalDialog(id="PrjDeleteDlg", footer=list(
                 modalTriggerButton("PrjDeleteDlgBtn", "#PrjDeleteDlg","Yes"),
                 tags$button(type = "button", class = "btn btn-primary", 
                            'data-dismiss' = "modal", "No")))),
            h6(),tags$style(type="text/css","#delPrjActionMsg{color:darkred;}") 
          ),  # END Manage Project
          tabPanel("Downloads", h6(), 
            downloadButton("dlFVSDatadb","Input data base (all data)"),h6(),
            downloadButton("dlFVSOutdb", "Output data base (.db, all runs)"),h6(),
            downloadButton("dlFVSOutxlsx", "Output .xlsx for current run"),h6(),
            downloadButton("dlFVSRunkey","Keyword file for current run"),h4(),        
            checkboxGroupInput("dlZipSet","Set contents of FVSProjectData.zip",   
              zipList,selZip,inline=FALSE),  
            downloadButton("dlFVSRunZip","Download FVSProjectData.zip") 
          ) #END Downloads tabPanel                                        
        )  #END  tabsetPanel for toolsPan
      ),  ## END Project Tools
      tabPanel("Help",
       fixedRow(column(width=12,offset=0,
          h5(),div(style = 'overflow-y:scroll;height:550px;',uiOutput("uiHelpText"))))  
      ) #END help tab  
   ) #END of topPan
   ) ) #END of second big row and End of Column
  ) #end fixedPage
